#!/bin/sh

#g++ test_UDPServer.cpp -o test_UDPServer.x -std=c++11 -lSDL2 -lSDL2_net -I/usr/local/include/SDL2  -Wl,-rpath -Wl,/usr/local/lib
#g++ test_UDPClient.cpp -o test_UDPClient.x -std=c++11 -lSDL2 -lSDL2_net -I/usr/local/include/SDL2  -Wl,-rpath -Wl,/usr/local/lib



g++ test_UDPServer.cpp -o test_UDPServer.x -std=c++11 -O3 -lSDL2 -lSDL2_net -I/usr/local/include/SDL2  -Wl,-rpath -Wl,/usr/local/lib
g++ test_UDPClient.cpp -o test_UDPClient.x -std=c++11 -O3 -lSDL2 -lSDL2_net -I/usr/local/include/SDL2  -Wl,-rpath -Wl,/usr/local/lib



#COMMON="/home/prokop/git/SimpleSimulationEngine/cpp/common"
#g++ test_UDPNode_server.cpp -o test_UDPServer.x -std=c++11 -lSDL2_net -lSDL2 -I/usr/local/include/SDL2  -Wl,-rpath -Wl,/usr/local/lib
#g++ test_UDPNode_client.cpp -o test_UDPClient.x -std=c++11 -lSDL2_net -lSDL2 -lm -lGL -lGLU -I/usr/local/include/SDL2 -I$COMMON/math -I$COMMON/SDL2OGL -Wl,-rpath -Wl,/usr/local/lib


: '
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the -LLIBDIR
flag during linking and do at least one of the following:
   - add LIBDIR to the LD_LIBRARY_PATH environment variable
     during execution
   - add LIBDIR to the LD_RUN_PATH environment variable
     during linking
   - use the "-Wl,-rpath -Wl,LIBDIR" linker flag
   - have your system administrator add LIBDIR to "/etc/ld.so.conf"
'
