# === AUTO-DOC BEGIN ===
"""
@brief Validation: numerical flux integration of field_loop_rz vs analytic mutual inductance.

Verifies that integrating Bz over a disk (2*pi*r*Bz*dr) reproduces the analytic
mutual inductance M*I from calc_mutual_inductance, and that on-axis Bz matches the
textbook formula mu0*I*a^2/(2*(a^2+z^2)^1.5). Serves as the primary correctness check
for the B-field kernel in inductance_core. Uses np.trapezoid with fallback to np.trapz
for NumPy <2.0 compatibility.
"""
# === AUTO-DOC END ===

import numpy as np
import argparse
from inductance_core import field_loop_rz, calc_mutual_inductance, MU0

# np.trapezoid was added in NumPy 2.0; fall back to np.trapz for older versions
_trapezoid = getattr(np, 'trapezoid', None) or np.trapz

def integrate_flux_from_B(a_source, z_source, I_source, r_target, z_target, Nr=5000):
    """
    Numerically integrates the magnetic flux through a circle of radius r_target
    at z_target, generated by a source loop (a_source, z_source).
    
    Phi = Integral( B_z * 2 * pi * r * dr ) from 0 to r_target
    """
    # Create radial grid for integration
    # We avoid r=0 exactly just to be safe, though kernel handles it.
    r = np.linspace(1e-9, r_target, Nr)
    dr = r[1] - r[0]
    
    # Target Z is constant
    z = np.full_like(r, z_target)
    
    # Calculate B-field on this disk
    # Grid inputs need to be 2D for the kernel, but here we just have 1D arrays matching
    Rg, Zg = np.meshgrid(r, [z_target]) # Shape (1, Nr)
    Br, Bz = field_loop_rz(a_source, z_source, I_source, Rg, Zg)
    
    # Bz is shape (1, Nr), flatten it
    Bz_vals = Bz[0, :]
    
    # Integrate: sum( B_z * 2*pi*r * dr )
    # Using trapezoidal rule for better accuracy than simple sum
    integrand = Bz_vals * 2 * np.pi * r
    phi_num = _trapezoid(integrand, x=r)
    
    return phi_num

def check_mutual_consistency(R_src=1.0, Z_src=0.0, R_tgt=0.5, Z_tgt=0.5, I=1.0, Nr=5000):
    print(f"\n[Check] Mutual Flux Consistency")
    print(f"  Source: R={R_src}, Z={Z_src}, I={I}")
    print(f"  Target: R={R_tgt}, Z={Z_tgt} (Integration Disk)")

    # 1. Analytic Mutual Inductance (The 'Gold Standard' used in solver)
    M_analytic = calc_mutual_inductance(R_src, Z_src, R_tgt, Z_tgt)
    Phi_analytic = M_analytic * I

    # 2. Numerical Integration of B-field (The 'Field' used for forces/viz)
    Phi_numeric = integrate_flux_from_B(R_src, Z_src, I, R_tgt, Z_tgt, Nr=Nr)

    # Compare
    err = abs(Phi_numeric - Phi_analytic)
    rel_err = err / abs(Phi_analytic) if Phi_analytic != 0 else 0.0

    print(f"  Phi_Analytic (M*I) : {Phi_analytic:.12e}")
    print(f"  Phi_Numeric (Int B): {Phi_numeric:.12e}")
    print(f"  Relative Error     : {rel_err:.12e}")
    
    if rel_err < 1e-4:
        print("  => PASS: B-kernel matches Inductance-kernel.")
    else:
        print("  => FAIL: Inconsistency detected.")

def check_on_axis(a=1.0, I=1.0, z0=0.0):
    print(f"\n[Check] On-Axis Field Exactness")
    z_eval = z0 + 1.0
    r_eval = np.array([0.0])
    z_grid = np.array([z_eval])
    
    # Numeric
    Rg, Zg = np.meshgrid(r_eval, z_grid)
    _, Bz_num = field_loop_rz(a, z0, I, Rg, Zg)
    Bz_num = float(Bz_num[0,0])

    # Analytic
    dz = z_eval - z0
    Bz_exact = (MU0 * I * a**2) / (2.0 * (a**2 + dz**2)**1.5)

    rel_err = abs(Bz_num - Bz_exact) / Bz_exact
    print(f"  Bz_Analytic        : {Bz_exact:.12e}")
    print(f"  Bz_Numeric         : {Bz_num:.12e}")
    print(f"  Relative Error     : {rel_err:.12e}")

if __name__ == "__main__":
    # Test 1: Separated loops (like Cage vs Plasma)
    check_mutual_consistency(R_src=1.0, Z_src=0.0, R_tgt=1.0, Z_tgt=0.5)

    # Test 2: Concentric loops (like Plasma expanding inside Seed)
    check_mutual_consistency(R_src=2.0, Z_src=0.0, R_tgt=1.0, Z_tgt=0.0)

    # Test 3: Standard Axis check
    check_on_axis()